export const demoPreset = [
  {"type":"book.reset"},
  {"type":"spread.element.add.sticker","payload":{"shape":"mixbook","x":601.5,"y":155}},
  {"type":"spread.selection.move","payload":{"x":-3,"y":-16}},
  {"type":"spread.element.add.text","payload":{"x":388.5,"y":140,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":2,"text":"Pre-Flexit<br>Training Exercise<br>","x":325.5,"y":128,"width":126,"height":48}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[2],"exclusive":true}},
  {"type":"spread.selection.text.align","payload":{"align":1}},
  {"type":"spread.selection.move","payload":{"x":70,"y":-12}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.element.add.text","payload":{"x":417.5,"y":354,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":3,"text":"Authors:","x":385.75,"y":342,"width":63.5,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[3],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":72,"y":5}},
  {"type":"spread.elements.select","payload":{"elements":[],"exclusive":true}},
  {"type":"spread.element.add.text","payload":{"x":233.5,"y":265,"autosize":false}},
  {"type":"spread.element.edit.text","payload":{"elementId":4,"text":"Anatolie Rotaru<br>Petre Negrei<br>","x":8.5,"y":180,"width":450,"height":170}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[4],"exclusive":true}},
  {"type":"spread.selection.text.align","payload":{"align":1}},
  {"type":"spread.selection.move","payload":{"x":66,"y":196}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[4],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-2,"y":1}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.element.add.text","payload":{"x":331.5,"y":416,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":5,"text":"Mixbook 2016","x":278.921875,"y":404,"width":105.15625,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[5],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-45,"y":145}},
	{"type":"spread.elements.select","payload":{"elements":[5],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":5,"text":"© Mixbook 2016","x":225.1875,"y":549,"width":122.625,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":228.5,"y":64}},
  {"type":"spread.selection.move","payload":{"x":99,"y":-39}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":222.5,"y":159}},
  {"type":"spread.selection.move","payload":{"x":70,"y":-74}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":173.5,"y":207}},
  {"type":"spread.selection.move","payload":{"x":71,"y":-59}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":181.5,"y":283}},
  {"type":"spread.selection.move","payload":{"x":6,"y":-79}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":86.5,"y":293}},
  {"type":"spread.selection.move","payload":{"x":40,"y":-50}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":111.5,"y":180}},
  {"type":"spread.selection.move","payload":{"x":-53,"y":92}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":184.5,"y":412}},
  {"type":"spread.selection.move","payload":{"x":-185,"y":-124}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":30.5,"y":157}},
  {"type":"spread.selection.move","payload":{"x":-13,"y":43}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":118.5,"y":76}},
  {"type":"spread.selection.move","payload":{"x":-37,"y":104}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":119.5,"y":52}},
  {"type":"spread.selection.move","payload":{"x":25,"y":98}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":185.5,"y":37}},
  {"type":"spread.selection.move","payload":{"x":13,"y":70}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":82.5,"y":42}},
  {"type":"spread.selection.move","payload":{"x":159,"y":4}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":64.5,"y":60}},
  {"type":"spread.selection.move","payload":{"x":189,"y":-53}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":57.5,"y":44}},
  {"type":"spread.selection.move","payload":{"x":-36,"y":75}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":77.5,"y":48}},
  {"type":"spread.selection.move","payload":{"x":9,"y":55}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":109.5,"y":40}},
  {"type":"spread.selection.move","payload":{"x":38,"y":22}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":177.5,"y":18}},
  {"type":"spread.selection.move","payload":{"x":-18,"y":-9}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":63.5,"y":34}},
  {"type":"spread.selection.move","payload":{"x":-44,"y":1}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":83.5,"y":25}},
  {"type":"spread.element.add.sticker","payload":{"shape":"react","x":142.5,"y":119}},
  {"type":"spread.selection.move","payload":{"x":-12,"y":-6}},
	{"type":"spread.selection.clear","payload":null},
  {"type":"spread.element.add.text","payload":{"x":758.5,"y":112,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":26,"text":"PURPOSE","x":723.0234375,"y":100,"width":70.953125,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[26],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-42,"y":26}},
  {"type":"spread.element.add.text","payload":{"x":725.5,"y":267,"autosize":false}},
  {"type":"spread.element.edit.text","payload":{"elementId":27,"text":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.","x":500.5,"y":182,"width":450,"height":170}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[27],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":182,"y":-26}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.element.add.text","payload":{"x":787.5,"y":422,"autosize":true}},
	{"type":"spread.elements.select","payload":{"elements":[28],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":28,"text":"ACCEPTANCE CRITERIA","x":702.6484375,"y":410,"width":169.703125,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[28],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-18,"y":-67}},
  {"type":"spread.element.add.text","payload":{"x":718.5,"y":429,"autosize":false}},
  {"type":"spread.element.edit.text","payload":{"elementId":29,"text":"qw","x":493.5,"y":344,"width":450,"height":170}},
  {"type":"spread.elements.select.all","payload":null},
	{"type":"spread.elements.select","payload":{"elements":[29],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":29,"text":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.","x":493.5,"y":344,"width":450,"height":170}},
  {"type":"spread.elements.select","payload":{"elements":[],"exclusive":true}},
  {"type":"spread.elements.select","payload":{"elements":[29],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":191,"y":31}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[26,27,28,29],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":0,"y":-63}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[29],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":0,"y":3}},
  {"type":"spread.elements.select","payload":{"elements":[26],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":1,"y":0}},
  {"type":"spread.elements.select","payload":{"elements":[4],"exclusive":true}},
  {"type":"spread.element.add.sticker","payload":{"shape":"sonic","x":1126.5,"y":527}},
  {"type":"spread.selection.move","payload":{"x":9,"y":9}},
  {"type":"spread.element.add.text","payload":{"x":838.5,"y":502,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":31,"text":"let's&nbsp;","x":821.5,"y":490,"width":34,"height":24}},
	{"type":"spread.elements.select","payload":{"elements":[31],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":31,"text":"let's start","x":804.3203125,"y":490,"width":68.359375,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[31],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":221,"y":73}},
	{"type":"spread.elements.select","payload":{"elements":[31],"exclusive":true}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[31],"exclusive":true}},
  {"type":"spread.selection.text.align","payload":{"align":1}},
	{"type":"spread.elements.select","payload":{"elements":[31],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":31,"text":"...let's start","x":1012.5390625,"y":563,"width":81.140625,"height":24}},
  {"type":"spread.elements.select","payload":{"elements":[29],"exclusive":true}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"book.spread.select","payload":{"spreadIndex":1}},
  {"type":"spread.element.add.text","payload":{"x":288.5,"y":106,"autosize":true}},
  {"type":"spread.elements.select","payload":{"elements":[32],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":32,"text":"We've started with these 3 basic shapes:","x":138.703125,"y":94,"width":299.59375,"height":24}},
  {"type":"spread.elements.select","payload":{"elements":[],"exclusive":true}},
  {"type":"spread.elements.select","payload":{"elements":[32],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":4,"y":-21}},
  {"type":"spread.elements.select","payload":{"elements":[],"exclusive":true}},
  {"type":"spread.element.add.sticker","payload":{"shape":"square","x":141.5,"y":237}},
  {"type":"spread.selection.move","payload":{"x":-17,"y":-27}},
  {"type":"spread.element.add.sticker","payload":{"shape":"circle","x":309.5,"y":238}},
  {"type":"spread.selection.move","payload":{"x":-9,"y":-29}},
  {"type":"spread.element.add.sticker","payload":{"shape":"triangle","x":427.5,"y":207}},
  {"type":"spread.selection.move","payload":{"x":38,"y":5}},
  {"type":"spread.element.add.text","payload":{"x":278.5,"y":374,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":36,"text":"Using them, we have developed basic functionality","x":90.5625,"y":362,"width":375.875,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[36],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":20,"y":-35}},
  {"type":"spread.elements.select","payload":{"elements":[36],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":36,"text":"Using them, we have developed basic functionality, like moving","x":64.1171875,"y":327,"width":468.765625,"height":24}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[34],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":119,"y":2}},
  {"type":"spread.elements.select","payload":{"elements":[35],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-169,"y":-2}},
  {"type":"spread.elements.select","payload":{"elements":[34],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":45,"y":0}},
  {"type":"spread.elements.select","payload":{"elements":[33],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":178,"y":1}},
  {"type":"spread.elements.select","payload":{"elements":[35],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-175,"y":0}},
  {"type":"spread.elements.select","payload":{"elements":[33],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-9,"y":2}},
  {"type":"spread.elements.select","payload":{"elements":[34],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-261,"y":-47}},
  {"type":"spread.elements.select","payload":{"elements":[35],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":335,"y":2}},
  {"type":"spread.elements.select","payload":{"elements":[34],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-78,"y":49}},
  {"type":"spread.element.add.text","payload":{"x":303.5,"y":419,"autosize":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":37,"text":"or changing","x":259.546875,"y":407,"width":87.90625,"height":24}},
  {"type":"spread.elements.select","payload":{"elements":[37],"exclusive":true}},
  {"type":"spread.element.edit.text","payload":{"elementId":37,"text":"or changing z-index...","x":224.25,"y":407,"width":158.5,"height":24}},
  {"type":"spread.elements.select","payload":{"elements":[],"exclusive":true}},
  {"type":"spread.elements.select","payload":{"elements":[37],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-13,"y":-41}},
  {"type":"spread.selection.clear","payload":null},
  {"type":"spread.element.add.sticker","payload":{"shape":"homer-simpson","x":184.5,"y":229}},
  {"type":"spread.selection.move","payload":{"x":-12,"y":-14}},
  {"type":"spread.elements.select","payload":{"elements":[34],"exclusive":true}},
  {"type":"spread.selection.bringToFront","payload":null},
  {"type":"spread.selection.bringToBack","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[33],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-108,"y":-1}},
  {"type":"spread.elements.select","payload":{"elements":[35],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":-244,"y":0}},
  {"type":"spread.elements.select","payload":{"elements":[38],"exclusive":true}},
  {"type":"spread.selection.sendBackward","payload":null},
  {"type":"spread.selection.sendBackward","payload":null},
  {"type":"spread.selection.sendBackward","payload":null},
  {"type":"spread.selection.sendBackward","payload":null},
  {"type":"spread.selection.sendBackward","payload":null},
  {"type":"spread.selection.sendForward","payload":null},
  {"type":"spread.selection.sendForward","payload":null},
  {"type":"spread.selection.sendForward","payload":null},
  {"type":"spread.selection.sendForward","payload":null},
  {"type":"spread.selection.sendForward","payload":null},
  {"type":"spread.elements.select","payload":{"elements":[35],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":239,"y":0}},
  {"type":"spread.elements.select","payload":{"elements":[33],"exclusive":true}},
  {"type":"spread.selection.move","payload":{"x":108,"y":0}},
  {"type":"spread.elements.select","payload":{"elements":[37],"exclusive":true}},
];

export function playPreset(dispatchFn: (action: {}) => void,  speed: number = 100): number {
  let preset = demoPreset.slice(0);

  let intervalId = setInterval(() => {
    let command = preset.shift();
    if (command) {
      dispatchFn(command);
    } else {
      clearInterval(intervalId);
    }
  }, speed);
  return intervalId;
}
